# This workflow will build a Java project with Gradle
# This file was contributed by ysenih@erpya.com from ERP Consultores y Asociados, C.A
# This file was contributed by EdwinBetanc0urt@outlook.com https://github.com/EdwinBetanc0urt
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
# Add support to default build

name: Continuous Integration with Gradle

on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
    paths-ignore:
      - README.md
      - README.es.md

  pull_request:
    branches:
      - main
      - master
      - develop
      - experimental
      - bugfix/**
      - hotfix/**
      - feature/**
    paths-ignore:
      - README.md
      - README.es.md

jobs:

  build-ci:
    name: Build with Gradle
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-package: 'jdk'
          java-version: 17
          architecture: x64

      - name: Setup Gradle 9
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: current # 9.0.0

      - name: Build with Gradle
        run: gradle build
        env:
          ORG_GRADLE_PROJECT_deployUsername: ${{ secrets.DEPLOY_USER }}
          ORG_GRADLE_PROJECT_deployToken: ${{ secrets.DEPLOY_TOKEN }}
          ORG_GRADLE_PROJECT_deployRepository: ${{ secrets.DEPLOY_REPOSITORY }}
          GITHUB_DEPLOY_USER: ${{ github.actor }}
          GITHUB_DEPLOY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_DEPLOY_REPOSITORY: ${{ secrets.DEPLOY_REPOSITORY }}

      - name: Upload descriptor file artifact
        uses: actions/upload-artifact@v4
        with:
          name: pos-homologation-service.dsc
          path: build/descriptors/pos-homologation-service.dsc
          retention-days: 1

      - name: Debug permissions
        run: |
          echo "Permisos actuales:"
          echo "${{ toJSON(github.token_permissions) }}"
          echo "¿Tiene contents:write? ${{ contains(fromJSON(toJSON(github.token_permissions)).contents, 'write') }}"

      - name: Verify token scope
        run: |
          RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/$GITHUB_REPOSITORY)
          PERMISSIONS=$(echo "$RESPONSE" | jq -r '.permissions')
          echo "Permisos actuales: $PERMISSIONS"
          if [[ $(echo "$PERMISSIONS" | jq -r '.contents') == "write" ]]; then
            echo "✅ contents:write confirmado";
          else
            echo "❌ Falta contents:write";
            exit 1;
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
